### ISSUE TITLE
Sentinel pool closing mechanism is not goroutine safe

### ISSUE THREAD

**Issue by dineshpanchananam** [FZambia/sentinel#2]
doUntilSuccess error closes the Pool shared by all other goroutines.

Pool close: https://github.com/FZambia/sentinel/blob/master/sentinel.go#L228
Pool Get: https://github.com/FZambia/sentinel/blob/master/sentinel.go#L167

This will lead to error logs like:
time="2019-06-05T13:58:42Z" level=error msg="redigo: no sentinels available; last error: redigo: get on closed pool"

**Comment by FZambia** [comment]
@dineshpanchananam thanks for report, I missed notification somehow. Actually my first question here is why we close pool at that place – I can't find a good reason to do this at moment.

**Comment by dineshpanchananam** [comment]
@FZambia From my testing, this happens when the request to fetch current MASTER_IP or SLAVE_IPS times out. Yes, there is no need to close the pool, close the connection maybe?

**Comment by FZambia** [comment]
> Yes, there is no need to close the pool, close the connection maybe?

We already close connection [here](https://github.com/FZambia/sentinel/blob/master/sentinel.go#L221). Or what do you mean?

My concern is that it's not actually required to close pool after each error, at least I can't understand why I did it this way. Need to test it out.

**Comment by dineshpanchananam** [comment]
My oversight. Yes, we are closing the connection there. 
But you are also right that we should never close the pool during runtime.

**Comment by FZambia** [comment]
@dineshpanchananam thanks for your help! Created tag v1.1.0 with fix from #3

**Comment by dineshpanchananam** [comment]
No problem!
