### ISSUE TITLE
Does it support redis module command?

### ISSUE THREAD

**Issue by githubname1024** [FZambia/sentinel#8]
I want to exec redis module command. Does this client support redis module command, for example redisearch?
Thank you very much.

**Comment by FZambia** [comment]
Hello @githubname1024 

It seems you are looking for general Redis client library, this is a package that only works with Redis Sentinel. You can take a look at the following Redis client packages to communicate with Redis:

* https://github.com/gomodule/redigo
* https://github.com/go-redis/redis
* https://github.com/rueian/rueidis
